# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f4c8d42b28f1fa469f35401809fb7a529c030abfbf6a35e822b7c2af7e14164dcc6ec30eecd573a83425ec3f0c6941fe568d845938ca9704cc218bb4d415dc

test:
  secret_key_base: 9428c69b8bf28721adc64e7a5c6c8824885da3d953e7d96950696e7193f24576dff0003f8d4e50f7b2bc5e139b86225737cb2a8a245b08ebb40728a0ac563dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
